### ISSUE TITLE
3d land crashes the app

### ISSUE THREAD

**Issue by joseepoiu** [emuPlace/emuThreeDS#114]

**Comment by Jeenvries** [comment]
Known issue since there is no Mii support rn.
You can follow this workaround:

**To fix the keyboard crash, you'll need to**
1. Import your (dumped) AES keys into a pc version of Citra
   a. Copy this file to the sysdata folder in your Citra user directory.
2. Launch Citra and go to Emulation > Configure > System
3. Select your region and New 3DS (others may work, haven't tried) > Download
4. When it finishes, go to File > Open Citra Folder and copy everything in there to your Emuthreeds folder on your apple device.
You now have a working keyboard in your games.

**Fixing Mii's**
1. Follow the keyboard crash fix first
2. Dump a Mii Maker CCI and place it in your roms folder
3. Launch it and go create your Mii and save everything
You now can use Mii's in game
