### ISSUE TITLE
emuThreeDS is violating the GPL license

### ISSUE THREAD

**Issue by FearlessTobi** [emuPlace/emuThreeDS#25]
Hello there,

I'm opening this issue to inform you that your project is violating Citra's GPL license.
As a copyleft license, the GPL requires you to distribute your source code, or a notice to request it with every single release.

This repository is distributing IPAs containing Citras code, but not the full source for it.
Please fix this as soon as possible.

**Comment by UnrealStudent2** [comment]
apologies but, you seem to have one braincell. This project is sanctioned by Citra, and the reason it is not open source is because of the fact that Antique is scared that all of their hard work will be stolen by Egg NS, and the way your asking about this when nobody else has had an issue might be because you yourself are trying to steal the code.

**Comment by sakuramipha** [comment]
@UnrealStudent2 You do realise that Tobi is a Citra developer speaking on behalf of the project as a whole, right?

**Comment by deformedRat** [comment]
@UnrealStudent2. There's no reason to be immature, especially when you're wrong.

**Comment by UnrealStudent2** [comment]
Oh just saw the new comments, apologies did not realize that, I don't know much about licenses and all of that. Again I am very sorry for being so rude and informal.

**Comment by Efadd** [comment]
Hey, uh, Tobi, we know, Antique knows, but he's trying to sidestep it just enough to keep a certain predatory emulation group off his back who will steal his code as they have Citra's and add it to the 90 dollar dlc with their controller.

**Comment by official-antique** [comment]
Fixed in second latest commit.
